import { Asset } from 'expo-asset';
import * as FileSystem from 'expo-file-system';
import type { MedicalRecord } from '../types';

const BRAND_BLUE = '#0284c7';
const BRAND_DARK = '#0f172a';

let logoDataUriCache: string | null = null;

/**
 * Loads the Sahatak logo as a base64 data URI so it can be embedded
 * directly into the print HTML (works fully offline).
 */
export async function getLogoDataUri(): Promise<string> {
  if (logoDataUriCache) return logoDataUriCache;
  try {
    const asset = Asset.fromModule(require('../../assets/sahatak-logo.png'));
    if (!asset.downloaded) {
      await asset.downloadAsync();
    }
    const localUri = asset.localUri ?? asset.uri;
    const base64 = await FileSystem.readAsStringAsync(localUri, {
      encoding: FileSystem.EncodingType.Base64,
    });
    logoDataUriCache = `data:image/png;base64,${base64}`;
  } catch (e) {
    console.warn('Could not load Sahatak logo for PDF:', e);
    logoDataUriCache = '';
  }
  return logoDataUriCache;
}

const esc = (s: string | undefined | null): string =>
  (s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

interface ReportTexts {
  docTitle: string;
  patientLabel: string;
  doctorLabel: string;
  specialtyLabel: string;
  dateLabel: string;
  statusLabel: string;
  clinicLabel: string;
  summaryLabel: string;
  medicinesLabel: string;
  medicineHeaders: [string, string, string, string];
  footerNote: string;
  generatedBy: string;
}

const TEXTS: Record<'en' | 'ar', ReportTexts> = {
  en: {
    docTitle: 'Medical Document',
    patientLabel: 'Patient',
    doctorLabel: 'Doctor',
    specialtyLabel: 'Specialty',
    dateLabel: 'Date',
    statusLabel: 'Status',
    clinicLabel: 'Facility',
    summaryLabel: 'Clinical Summary & Findings',
    medicinesLabel: 'Itemized Prescription',
    medicineHeaders: ['Medicine', 'Dosage & Frequency', 'Duration', 'Instructions'],
    footerNote:
      'This document is generated by the Sahatak telemedicine platform and is for informational purposes only. It does not replace urgent medical care.',
    generatedBy: 'Generated by Sahatak • sahatak telemedicine platform',
  },
  ar: {
    docTitle: 'مستند طبي',
    patientLabel: 'المريض',
    doctorLabel: 'الطبيب',
    specialtyLabel: 'التخصص',
    dateLabel: 'التاريخ',
    statusLabel: 'الحالة',
    clinicLabel: 'المنشأة',
    summaryLabel: 'الملخص السريري والنتائج',
    medicinesLabel: 'تفاصيل الوصفة',
    medicineHeaders: ['الدواء', 'الجرعة والتكرار', 'المدة', 'التعليمات'],
    footerNote:
      'هذا المستند صادر عن منصة صحتك للطب عن بُعد ولأغراض المعلومات فقط، ولا يُغني عن الرعاية الطبية الطارئة.',
    generatedBy: 'صادر عن منصة صحتك • منصة الطب عن بُعد',
  },
};

const infoRow = (label: string, value: string) =>
  value
    ? `<tr>
         <td style="padding:6px 10px;font-size:12px;font-weight:700;color:${BRAND_DARK};white-space:nowrap;">${esc(label)}</td>
         <td style="padding:6px 10px;font-size:12px;color:#334155;">${value}</td>
       </tr>`
    : '';

export async function buildMedicalRecordHtml(
  record: MedicalRecord,
  lang: 'en' | 'ar',
  patientName?: string,
): Promise<string> {
  const T = TEXTS[lang];
  const rtl = lang === 'ar';
  const dir = rtl ? 'rtl' : 'ltr';
  const logo = await getLogoDataUri();

  const title = esc(rtl ? record.titleAr : record.title);
  const doctor = esc(rtl ? record.doctorNameAr : record.doctorName);
  const specialty = esc(rtl ? record.doctorSpecialtyAr : record.doctorSpecialty);
  const date = esc(rtl ? record.dateAr : record.date);
  const status = esc(rtl ? record.statusAr : record.status);
  const clinic = esc(rtl ? record.facilityAr || record.clinicNameAr : record.facility || record.clinicName);
  const summaryValues = rtl
    ? [record.diagnosisSummaryAr || record.diagnosisSummary, record.diagnosisAr || record.diagnosis]
    : [record.diagnosisSummary, record.diagnosis];
  const summary = esc(
    record.type === 'consultation_summary' || record.type === 'diagnosis'
      ? summaryValues.filter(Boolean).join('\n\n')
      : summaryValues[0] || '',
  );

  const medicinesRows = (record.medicines ?? [])
    .map(
      (m) => `<tr>
        <td style="padding:8px 10px;font-size:12px;font-weight:700;color:${BRAND_BLUE};border-bottom:1px solid #e2e8f0;">${esc(rtl ? m.nameAr : m.name)}</td>
        <td style="padding:8px 10px;font-size:12px;color:#334155;border-bottom:1px solid #e2e8f0;">${esc(rtl ? m.dosageAr : m.dosage)}<br/><span style="font-size:11px;color:#64748b;">${esc(rtl ? m.frequencyAr : m.frequency)}</span></td>
        <td style="padding:8px 10px;font-size:12px;color:#334155;border-bottom:1px solid #e2e8f0;">${esc(rtl ? m.durationAr : m.duration)}</td>
        <td style="padding:8px 10px;font-size:11px;color:#64748b;border-bottom:1px solid #e2e8f0;">${esc(rtl ? m.instructionsAr : m.instructions)}</td>
      </tr>`,
    )
    .join('');

  const [h1, h2, h3, h4] = T.medicineHeaders;

  const medicinesSection =
    record.medicines && record.medicines.length > 0
      ? `<h2 style="font-size:14px;color:${BRAND_DARK};margin:18px 0 8px;border-bottom:2px solid ${BRAND_BLUE};padding-bottom:4px;">${esc(T.medicinesLabel)}</h2>
         <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;border:1px solid #e2e8f0;">
           <tr>
             <th style="background:#f0f9ff;padding:8px 10px;font-size:11px;text-align:${rtl ? 'right' : 'left'};color:${BRAND_DARK};">${esc(h1)}</th>
             <th style="background:#f0f9ff;padding:8px 10px;font-size:11px;text-align:${rtl ? 'right' : 'left'};color:${BRAND_DARK};">${esc(h2)}</th>
             <th style="background:#f0f9ff;padding:8px 10px;font-size:11px;text-align:${rtl ? 'right' : 'left'};color:${BRAND_DARK};">${esc(h3)}</th>
             <th style="background:#f0f9ff;padding:8px 10px;font-size:11px;text-align:${rtl ? 'right' : 'left'};color:${BRAND_DARK};">${esc(h4)}</th>
           </tr>
           ${medicinesRows}
         </table>`
      : '';

  return `<!DOCTYPE html>
<html dir="${dir}" lang="${lang}">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>${title}</title>
</head>
<body style="margin:0;padding:24px;background:#ffffff;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Arial,sans-serif;color:${BRAND_DARK};">
  <table width="100%" cellpadding="0" cellspacing="0" style="max-width:640px;margin:0 auto;border-collapse:collapse;">
    <tr>
      <td style="text-align:center;padding-bottom:12px;border-bottom:3px solid ${BRAND_BLUE};">
        ${logo ? `<img src="${logo}" alt="Sahatak" width="72" height="72" style="display:block;margin:0 auto 6px;" />` : ''}
        <div style="font-size:20px;font-weight:800;color:${BRAND_BLUE};">Sahatak <span style="font-weight:600;">صحتك</span></div>
        <div style="font-size:11px;color:#64748b;">${esc(T.generatedBy)}</div>
      </td>
    </tr>
    <tr>
      <td style="text-align:center;padding:16px 0 4px;">
        <div style="font-size:17px;font-weight:800;">${title}</div>
        <div style="font-size:11px;color:#0ea5e9;font-weight:700;margin-top:2px;">${esc(T.docTitle)} • ${esc(status)}</div>
      </td>
    </tr>
    <tr>
      <td style="padding:12px 0;">
        <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;background:#f8fafc;border:1px solid #e2e8f0;">
          ${infoRow(T.patientLabel, esc(patientName || ''))}
          ${infoRow(T.doctorLabel, doctor)}
          ${infoRow(T.specialtyLabel, specialty)}
          ${infoRow(T.dateLabel, date)}
          ${infoRow(T.clinicLabel, clinic)}
        </table>
      </td>
    </tr>
    ${
      summary
        ? `<tr>
             <td style="padding:4px 0 12px;">
               <h2 style="font-size:14px;color:${BRAND_DARK};margin:0 0 8px;border-bottom:2px solid ${BRAND_BLUE};padding-bottom:4px;">${esc(T.summaryLabel)}</h2>
               <p style="font-size:12px;line-height:1.7;color:#334155;margin:0;">${summary}</p>
             </td>
           </tr>`
        : ''
    }
    ${medicinesSection ? `<tr><td>${medicinesSection}</td></tr>` : ''}
    <tr>
      <td style="padding-top:20px;border-top:1px solid #e2e8f0;">
        <p style="font-size:10px;color:#94a3b8;line-height:1.6;text-align:center;margin:0;">${esc(T.footerNote)}</p>
      </td>
    </tr>
  </table>
</body>
</html>`;
}
